Add undocumented SetHash methods
Raku/doc pull request #3572
Opened 2020-08-20 15:25 UTC by codesections

This PR adds the following 16 methods to `SetHash`: `clone`, `grab`, `grabpairs`, `iterator`, `kv`, `set`, `unset`, `values`, `Baggy`, `Mixy`, `Set`, `SetHash`, `Setty`, `AT-KEY`, `DELETE-KEY`, and `STORE`.  Adding these methods means that `SetHash` currently has no undocumented methods.  The PR also adds a bit of text to the overview describing how the contents of a `SetHash` can be altered with the `set` and `unset` methods.

I wasn't entirely sure whether to add all methods.  Many methods are specialized implementations of methods already provided/stubbed higher in the dependency graph.  Please let me know if there are any that you think should be left undocumented, I will delete them.   However, I decided to document all methods for reasons basically analogous to those brought up in #3209: these methods really are implemented in `SetHash` (i.e., they both appear in the source code and live in its local methods table), and anyone subclassing/augmenting/etc `SetHash` may want to know that.

Given the number of added methods, however, I decided to depart from strict case-intensive ordering (which seemed to be the tentative consensus emerging from #392).  Instead, I put the three ALL-CAPS methods that are called automatically via `{ }` at the end; above those, I put the IntialCapital coercion methods, and then put all the other methods above that (the methods are alphabetical within their respective groups).  I believe this keeps methods clearly organized while also helping keep less user-facing methods away from the top of the list.  But I'm open to other thoughts on this as well.

This PR goes halfway to resolving #3569.

2020-08-20 15:36 UTC, lizmat commented
Feels to me that `clone`, `iterator`, `AT-KEY`, `DELETE-KEY` and `STORE` would not need to be documented here.

2020-08-20 15:42 UTC, codesections commented
> Feels to me that `clone`, `iterator`, `AT-KEY`, `DELETE-KEY` and `STORE` would not need to be documented here.

Ok, I'm definitely happy to take them out.  What's the principle that lets you pull out those five for exclusion?  They all do what a user would expect them to do, so I agree that documenting them doesn't add a whole lot.  But the same could be said of `Set`, so I'm not quite sure where we're drawing the line.  I'm asking  I plan to add missing methods to more types over the coming days/weeks, and I'd like to understand which methods I should be including.

2020-08-20 16:02 UTC, lizmat commented
Well, if `AT-KEY` and `DELETE-KEY` are document, so should at least `EXISTS-KEY` be as well as potentially `BIND-KEY`.

I'm not sure where the boundary is really.

2020-08-20 16:05 UTC, lizmat commented
Having test subs return their status, has the advantage that you can easily add a line before them with diagnostic info.  So suppose you have:

    ok Foo ~~ Bar;

you can do something like:

    diag "WTF is happening here" unless
    ok Foo ~~ Bar;

to get extra, non-standard diagnostics.

2020-08-20 17:20 UTC, codesections commented
> Well, if `AT-KEY` and `DELETE-KEY` are documented, so should at least `EXISTS-KEY` be as well as potentially `BIND-KEY`.
> I'm not sure where the boundary is really.

Right now (in the PR as it exists), the boundary is "document anything that exists _in the type_ being documented" (in the current Rakudo implementation).  `EXISTS-KEY` is not implemented in `SetHash`: running `SetHash.^lookup('EXISTS-KEY').candidates».package` shows that `SetHash` has `EXIST-KEY` methods from `Any` and `Setty` in its MRO, and grepping over the Rakudo source code confirms that it's not in the `SetHash.pm6` file.  Similarly, `SetHash` gets `BIND-KEY` from `Any`.  In contrast, [`STORE`](https://github.com/rakudo/rakudo/blob/master/src/core.c/SetHash.pm6#L206-L231), [`AT-KEY`](https://github.com/rakudo/rakudo/blob/master/src/core.c/SetHash.pm6#L233-L258), and [`DELETE-KEY`](https://github.com/rakudo/rakudo/blob/master/src/core.c/SetHash.pm6#L260-L271) are all implemented in `SetHash` itself.

I'm not _sure_ that "exists in the Rakudo source" is the right place to draw the line – it's a bit implementation dependent, for one thing and, at least arguably, the choice to locally implement `AT-KEY` but not `EXISTS-KEY` could be viewed as an implementation detail.

So I'm open to drawing the line somewhere else.  But I'd like to have a clear way to draw the line, and right now the only idea I've come up with is "is it in the source/local to the type".  If we can come up with a better line, though, I'll be all for it – especially if it means we have fewer methods that need documenting!

2020-08-20 21:03 UTC, lizmat commented
`SetHash.EXISTS-KEY` lives in the `Setty` role, **not** in `Any`.

My opinion wrt documentation of classes, is to document what is user-facing.  In that sense, all of the `UPPER-CASE` methods are implementation details.  But where to draw the line, I'm not sure.  I mean, do we document the `Bool` method on a `SetHash` ?  Or the `Int` method?  Or the `defined` method?  Etc. Etc.  In a world without inheritance or mixins, this would all be so much simpler :-)

2020-08-20 21:38 UTC, codesections commented
> `SetHash.EXISTS-KEY` lives in the `Setty` role, **not** in `Any`.

I agree.  That's why I said that "`SetHash` has `EXIST-KEY` methods from `Any` and `Setty` in its MRO" – and it's certainly correct that the one from `Setty` is the one that's called with a basic call to `SetHash.EXIST-KEY`.

> My opinion wrt documentation of classes, is to document what is user-facing.

I also agree with that – but I guess the real question is what do we mean by "user"?  I guess my thought was that users of Raku are, by definition, Raku programmers and might be inclined to do things implement complex type inheritance and/or mess with meta objects.  But maybe documenting `UPPER-CASE` methods is carrying that too far.

So, how about this as a general rule: for each Type, we document a method if it is: 1) public, 2) defined in that class (rather than inherited), 3) not an `UPPER-CASE` method, and 4) not flagged with the `is implementation detail` trait.  That would mean that we would **not** document `Bool`, `Int`, or `defined` in `SetHash`, since none of those methods is defined in the `SetHash` class (they're inherited from `Mu` or `QuantHash`).

Does that four-part rule seem like a good place to draw the line to you/anyone else following this conversation?

2020-08-21 06:17 UTC, JJ commented
El jue., 20 ago. 2020 a las 23:41, Daniel Sockwell (<
notifications@github.com>) escribió:

> SetHash.EXISTS-KEY lives in the Setty role, *not* in Any.
>
> I agree. That's why I said that "SetHash has EXIST-KEY methods from Any
> and Setty in its MRO" – and it's certainly correct that the one from Setty
> is the one that's called with a basic call to SetHash.EXIST-KEY.
>
> My opinion wrt documentation of classes, is to document what is
> user-facing.
>
> I also agree with that – but I guess the real question is what do we mean
> by "user"? I guess my thought was that users of Raku are, by definition,
> Raku programmers and might be inclined to do things implement complex type
> inheritance and/or mess with meta objects. But maybe documenting
> UPPER-CASE methods is carrying that too far.
>
> So, how about this as a general rule: for each Type, we document a method
> if it is: 1) public, 2) defined in that class (rather than inherited), 3)
> not an UPPER-CASE method, and 4) not flagged with the is implementation
> detail trait. That would mean that we would *not* document Bool, Int, or
> defined in SetHash, since none of those methods is defined in the SetHash
> class (they're inherited from Mu or QuantHash).
>
> Does that four-part rule seem like a good place to draw the line to
> you/anyone else following this conversation?
>

That might or might not seem a good place, but *this PR* is not. While we
can agree in some of them, sometimes lines are not so clear-cut.
Definitely, "is implementation-detail" should not be documented. But about
the rest, YMMV. In general, if they are public they are game.
So I'd suggest we stick to this specific PR for the time being, and maybe
draft an issue to modify the CONTRIBUTING document with these details.

2020-08-21 06:22 UTC, JJ requested changes
Please chck out the comments.

2020-08-21 06:22 UTC, JJ commented on doc/Type/SetHash.pod6
> +the provided key or keys are present in the C<Set>.  This method is
If it returns a list, how come it be defined with a single Bool as return type?

2020-08-24 17:37 UTC, closed without merging