Make user aware of the risk of using qqx
Raku/doc pull request #3696
Opened 2020-11-16 11:57 UTC by hythm7

## The problem

It is not clear from `qqx` examples that it can be used to execute arbitrary code if the user did not take the necessary precautions to prevent such issue.

## Solution provided

Add example in traps page to show how the content of a variable used by `qqx` can be used to execute malicious code, also warned the user about it in quoting page. so that the user is aware of such cases before deciding to use `qqx`

Note: please let me know about any grammar/punctuation corrections.

2020-11-16 12:07 UTC, JJ commented
Please mention at least the problem-solving issue it comes from.

2020-11-16 12:09 UTC, JJ requested changes
I know it's still in draft, but you might want to have a look at these comments.

2020-11-16 12:09 UTC, JJ commented on doc/Language/quoting.pod6
> +Be aware of the content of the Raku variable used within an external command; malicious content can be used to execute arbitrary code. See L<qqx traps|/language/traps/Beware_of_variables_used_within_
Use `C<qqx>` to make it `qqx`

2020-11-16 12:09 UTC, JJ commented on doc/Language/traps.pod6
> +
This should probably not be a full stop, but a simple comma or nothing.

2020-11-16 12:11 UTC, JJ commented
This is also related to the former "taint" mode in Perl. There's a
reference for that in the documentation, which directs you to this reddit
thread https://www.reddit.com/r/perl6/comments/718z4o/taint_mode_for_perl_6/

2020-11-16 13:35 UTC, coke commented
Thank you for running the tests - if no new tests fail, it's not your fault, no worries.

2020-11-16 13:41 UTC, coke commented
On master, that test is passing.

2022-04-17 17:10 UTC, JJ approved these changes
:+1: 
Thanks for making the changes!

2022-04-17 17:10 UTC, JJ commented
Is this still a draft?

2022-11-14 03:29 UTC, coke approved these changes

2022-11-14 03:30 UTC, merged

2022-11-14 03:30 UTC, coke commented
rescued from draft and merged, thanks. I think all JJ's items were addressed but not marked resolved.