Some tweaks on CATCH
Raku/doc pull request #4050
Opened 2022-04-07 19:10 UTC by lizmat

In response to https://github.com/Raku/doc/issues/4049

2022-04-07 21:31 UTC, coke commented
The updated examples don't compile cleanly, you can see the output with

```
TEST_FILES=doc/Language/exceptions.pod6 make xtest
```

I am happy to make them work in the branch or post-merge. (Need to wrap in an explicit pod block and predeclare some things, I think)

2022-04-08 05:31 UTC, JJ requested changes
Since @japhb and @coke have pointed a couple of things that could be changed, I'll go for requesting changes; however, none of my comments are actually blockers. Thanks a lot!

2022-04-08 05:31 UTC, JJ commented on doc/Language/exceptions.pod6
> +Note that the C<CATCH> block semantics apply to the B<entire> lexical scope
Starts with the same word as above. Consider alternatives "Please also" or "Note also"

2022-04-08 05:31 UTC, JJ commented on doc/Language/exceptions.pod6
> +in the same namespace will look alike but won't match in a C<CATCH> block.
I don't quite understand this sentence. It was there prior to this PR, but as long as you're editing it, some nits
1. Not clear what's that precise role you're mentioning.
2. The second sentence is difficult to parse. It refers to the existence of what? Will look like what?

2022-04-08 05:31 UTC, JJ commented on doc/Language/exceptions.pod6
> +of the code can immediately see that there is something special going on.
This clarification is on point, but it might be better right after the example, or alternatively providing another example.

2022-04-08 15:26 UTC, coke commented
at @lizmat's request, I fixed the examples and the typos in this branch. Might have to manually merge it to get those fixes?

2022-04-08 15:38 UTC, coke commented
I did push before I posted. was asked if I wanted to make *another* PR, which I didn't.

2022-04-08 18:33 UTC, JJ commented
> I did push before I posted. was asked if I wanted to make _another_ PR, which I didn't.

I'm confused. There's only one commit in this branch, and it's by @lizmat

2022-04-08 19:36 UTC, coke commented
branch differs by case only. fixing.

2022-04-09 19:10 UTC, JJ approved these changes
Thanks!

2022-04-09 19:10 UTC, merged