Simple typos, misphrasings, and punc
Raku/doc pull request #4081
Opened 2022-06-06 02:46 UTC by 0rir

Simple typos, misphrasings, and punctuation errors.

With problems little problems like these,  I think thirty changes would be a reasonably size pull request.   Absent feedback, I'll roughly double the count over the next two PRs to twenty.

Thanks.

2022-06-06 20:19 UTC, coke requested changes
I don't think the addition of 'the' is needed/correct here. Otherwise looks fine.

2022-06-07 01:59 UTC, 0rir commented
@coke, thanks for the catch.

2022-06-13 10:41 UTC, Altai-man approved these changes

2022-06-24 19:56 UTC, coke commented
Sorry for the delay, didn't see that the change had been made.

2022-06-24 19:56 UTC, merged