Update DateTime.pod6
Raku/doc pull request #4230
Opened 2023-03-01 17:55 UTC by finanalyst

## The problem
Link attached to 'propleptic' is tagged as a security hazard using Firefox,

## Solution provided

Replace link with similar content in Wikipedia.

2023-03-01 18:27 UTC, coke requested changes
Lost the https

2023-03-02 20:42 UTC, 2colours commented
Also - pretty sure it was just a typo from wik**t**ionary

2023-03-02 23:25 UTC, cfa commented
As @2colours pointed out, the intended link was probably https://en.wiktionary.org/wiki/proleptic.

2023-03-03 11:13 UTC, finanalyst commented
reverting to original, then correcting typo

2023-03-03 11:13 UTC, closed without merging